# Generated by Django 3.0.8 on 2020-08-03 08:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SignUpDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('PaymentID', models.CharField(blank=True, max_length=15, null=True)),
                ('SiteID', models.CharField(blank=True, max_length=10, null=True)),
                ('FirstName', models.CharField(blank=True, max_length=20, null=True)),
                ('LastName', models.CharField(blank=True, max_length=20, null=True)),
                ('Addr1', models.CharField(blank=True, max_length=30, null=True)),
                ('Addr2', models.CharField(blank=True, max_length=30, null=True)),
                ('State', models.IntegerField(blank=True, null=True)),
                ('ZipCode', models.IntegerField(blank=True, null=True)),
                ('CellPhone', models.CharField(max_length=10)),
                ('EmailAddr', models.CharField(max_length=35)),
                ('CarrierCode', models.IntegerField(blank=True, null=True)),
                ('APIKey', models.CharField(blank=True, max_length=40, null=True)),
                ('SEUsername', models.CharField(max_length=35)),
                ('SEPassword', models.CharField(max_length=35)),
            ],
        ),
    ]
