# Generated by Django 3.0.8 on 2020-08-06 23:45

import MySolarSentinelAPI.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySolarSentinelAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='CellPhone',
            field=models.CharField(max_length=17, validators=[MySolarSentinelAPI.models.validate_CellPhone]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='EmailAddr',
            field=models.CharField(max_length=35, validators=[MySolarSentinelAPI.models.validate_State]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='State',
            field=models.IntegerField(blank=True, null=True, validators=[MySolarSentinelAPI.models.validate_State]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ZipCode',
            field=models.IntegerField(blank=True, null=True, validators=[MySolarSentinelAPI.models.validate_ZipCode]),
        ),
    ]
