# Generated by Django 3.0.8 on 2020-08-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySolarSentinelAPI', '0002_auto_20200806_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='CarrierCode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
