# Generated by Django 3.0.8 on 2020-08-16 15:20

import MySolarSentinelAPI.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySolarSentinelAPI', '0003_auto_20200816_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='CarrierCode',
            field=models.IntegerField(validators=[MySolarSentinelAPI.models.validate_CarrierCode]),
        ),
    ]
