# Generated by Django 3.0.8 on 2020-09-15 05:56

import MySolarSentinelAPI.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySolarSentinelAPI', '0005_supporttickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Addr1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Addr2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='FirstName',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='LastName',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='State',
            field=models.IntegerField(null=True, validators=[MySolarSentinelAPI.models.validate_State]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ZipCode',
            field=models.IntegerField(null=True, validators=[MySolarSentinelAPI.models.validate_ZipCode]),
        ),
    ]
